# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      # Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

          
      # Install dependencies
      - name: Install dependencies
        run: |
            cd blog-app
            npm ci

      # Create .env file
      - name: Create .env file
        run: |
          pwd
          cd blog-app          
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env
          echo "FIREBASE_AUTH_DOMAIN=${{ vars.FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "FIREBASE_PROJECT_ID=${{ vars.FIREBASE_PROJECT_ID }}" >> .env
          echo "FIREBASE_STORAGE_BUCKET=${{ vars.FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ vars.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "FIREBASE_APP_ID=${{ vars.FIREBASE_APP_ID }}" >> .env
          cat .env

      # Build the project
      - name: Build
        run: |
            pwd
            cd blog-app            
            npm run build

      # Deploy to GitHub Pages
      - name: Deploy to gh page
        run: |
            cd blog-app
            npx angular-cli-ghpages --dir=dist/blog-app
        env:            
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}          
